# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(849, 982)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 70, 831, 901))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_applte = QtWidgets.QWidget()
        self.tab_applte.setObjectName("tab_applte")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_applte)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 162, 381))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vl_buttons_applte = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vl_buttons_applte.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.vl_buttons_applte.setContentsMargins(0, 0, 0, 0)
        self.vl_buttons_applte.setObjectName("vl_buttons_applte")
        self.fl_le_applte = QtWidgets.QFormLayout()
        self.fl_le_applte.setObjectName("fl_le_applte")
        self.label_x0 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_x0.setFont(font)
        self.label_x0.setObjectName("label_x0")
        self.fl_le_applte.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_x0)
        self.le_x0 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.le_x0.setObjectName("le_x0")
        self.fl_le_applte.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_x0)
        self.label_X = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_X.setFont(font)
        self.label_X.setObjectName("label_X")
        self.fl_le_applte.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_X)
        self.le_X = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.le_X.setObjectName("le_X")
        self.fl_le_applte.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_X)
        self.label_y0 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_y0.setFont(font)
        self.label_y0.setObjectName("label_y0")
        self.fl_le_applte.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_y0)
        self.le_y0 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.le_y0.setObjectName("le_y0")
        self.fl_le_applte.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_y0)
        self.label_N = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_N.setFont(font)
        self.label_N.setObjectName("label_N")
        self.fl_le_applte.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_N)
        self.le_N_applte = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.le_N_applte.setObjectName("le_N_applte")
        self.fl_le_applte.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.le_N_applte)
        self.vl_buttons_applte.addLayout(self.fl_le_applte)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.vl_buttons_applte.addWidget(self.line)
        self.cb_exact = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cb_exact.setChecked(True)
        self.cb_exact.setObjectName("cb_exact")
        self.vl_buttons_applte.addWidget(self.cb_exact)
        self.cb_eem = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cb_eem.setChecked(True)
        self.cb_eem.setObjectName("cb_eem")
        self.vl_buttons_applte.addWidget(self.cb_eem)
        self.cb_iem = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cb_iem.setObjectName("cb_iem")
        self.vl_buttons_applte.addWidget(self.cb_iem)
        self.cb_rkm = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cb_rkm.setObjectName("cb_rkm")
        self.vl_buttons_applte.addWidget(self.cb_rkm)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.vl_buttons_applte.addWidget(self.line_2)
        self.cb_eem_lte = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cb_eem_lte.setObjectName("cb_eem_lte")
        self.vl_buttons_applte.addWidget(self.cb_eem_lte)
        self.cb_iem_lte = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cb_iem_lte.setObjectName("cb_iem_lte")
        self.vl_buttons_applte.addWidget(self.cb_iem_lte)
        self.cb_rkm_lte = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cb_rkm_lte.setObjectName("cb_rkm_lte")
        self.vl_buttons_applte.addWidget(self.cb_rkm_lte)
        self.pb_plot_applte = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pb_plot_applte.setObjectName("pb_plot_applte")
        self.vl_buttons_applte.addWidget(self.pb_plot_applte)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_applte)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(200, 10, 611, 821))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.vl_graphs = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.vl_graphs.setContentsMargins(0, 0, 0, 0)
        self.vl_graphs.setObjectName("vl_graphs")
        self.gb_app = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.gb_app.setObjectName("gb_app")
        self.app_plot = QtWidgets.QWidget(self.gb_app)
        self.app_plot.setGeometry(QtCore.QRect(10, 30, 581, 371))
        self.app_plot.setObjectName("app_plot")
        self.vl_graphs.addWidget(self.gb_app)
        self.gb_lte = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.gb_lte.setObjectName("gb_lte")
        self.lte_plot = QtWidgets.QWidget(self.gb_lte)
        self.lte_plot.setGeometry(QtCore.QRect(10, 20, 581, 331))
        self.lte_plot.setObjectName("lte_plot")
        self.vl_graphs.addWidget(self.gb_lte)
        self.label_applte = QtWidgets.QLabel(self.tab_applte)
        self.label_applte.setGeometry(QtCore.QRect(20, 430, 160, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_applte.sizePolicy().hasHeightForWidth())
        self.label_applte.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_applte.setFont(font)
        self.label_applte.setAutoFillBackground(True)
        self.label_applte.setAlignment(QtCore.Qt.AlignCenter)
        self.label_applte.setWordWrap(True)
        self.label_applte.setObjectName("label_applte")
        self.label_applte_colors = QtWidgets.QLabel(self.tab_applte)
        self.label_applte_colors.setGeometry(QtCore.QRect(20, 550, 171, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_applte_colors.sizePolicy().hasHeightForWidth())
        self.label_applte_colors.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_applte_colors.setFont(font)
        self.label_applte_colors.setAutoFillBackground(False)
        self.label_applte_colors.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_applte_colors.setWordWrap(False)
        self.label_applte_colors.setObjectName("label_applte_colors")
        self.tabWidget.addTab(self.tab_applte, "")
        self.tab_gte = QtWidgets.QWidget()
        self.tab_gte.setObjectName("tab_gte")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_gte)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 20, 162, 194))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.vl_buttons_gte = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.vl_buttons_gte.setContentsMargins(0, 0, 0, 0)
        self.vl_buttons_gte.setObjectName("vl_buttons_gte")
        self.fl_le_gte = QtWidgets.QFormLayout()
        self.fl_le_gte.setObjectName("fl_le_gte")
        self.label_n0 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_n0.setFont(font)
        self.label_n0.setObjectName("label_n0")
        self.fl_le_gte.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_n0)
        self.le_n0 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.le_n0.setObjectName("le_n0")
        self.fl_le_gte.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_n0)
        self.label_N_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_N_2.setFont(font)
        self.label_N_2.setObjectName("label_N_2")
        self.fl_le_gte.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_N_2)
        self.le_N_gte = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.le_N_gte.setObjectName("le_N_gte")
        self.fl_le_gte.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_N_gte)
        self.vl_buttons_gte.addLayout(self.fl_le_gte)
        self.cb_eem_gte = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.cb_eem_gte.setChecked(True)
        self.cb_eem_gte.setObjectName("cb_eem_gte")
        self.vl_buttons_gte.addWidget(self.cb_eem_gte)
        self.cb_iem_gte = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.cb_iem_gte.setObjectName("cb_iem_gte")
        self.vl_buttons_gte.addWidget(self.cb_iem_gte)
        self.cb_rkm_gte = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.cb_rkm_gte.setObjectName("cb_rkm_gte")
        self.vl_buttons_gte.addWidget(self.cb_rkm_gte)
        self.pb_plot_gte = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pb_plot_gte.setObjectName("pb_plot_gte")
        self.vl_buttons_gte.addWidget(self.pb_plot_gte)
        self.gb_gte = QtWidgets.QGroupBox(self.tab_gte)
        self.gb_gte.setGeometry(QtCore.QRect(200, 10, 609, 366))
        self.gb_gte.setObjectName("gb_gte")
        self.gte_plot = QtWidgets.QWidget(self.gb_gte)
        self.gte_plot.setGeometry(QtCore.QRect(10, 20, 581, 331))
        self.gte_plot.setObjectName("gte_plot")
        self.label_gte = QtWidgets.QLabel(self.tab_gte)
        self.label_gte.setGeometry(QtCore.QRect(20, 230, 160, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_gte.sizePolicy().hasHeightForWidth())
        self.label_gte.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_gte.setFont(font)
        self.label_gte.setAutoFillBackground(True)
        self.label_gte.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gte.setWordWrap(True)
        self.label_gte.setObjectName("label_gte")
        self.label_gte_colors = QtWidgets.QLabel(self.tab_gte)
        self.label_gte_colors.setGeometry(QtCore.QRect(20, 370, 171, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_gte_colors.sizePolicy().hasHeightForWidth())
        self.label_gte_colors.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_gte_colors.setFont(font)
        self.label_gte_colors.setAutoFillBackground(False)
        self.label_gte_colors.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_gte_colors.setWordWrap(False)
        self.label_gte_colors.setObjectName("label_gte_colors")
        self.tabWidget.addTab(self.tab_gte, "")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 1151, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_x0.setText(_translate("Form", "<html><head/><body><p>x<span style=\" vertical-align:sub;\">0</span></p></body></html>"))
        self.le_x0.setText(_translate("Form", "1"))
        self.label_X.setText(_translate("Form", "X"))
        self.le_X.setText(_translate("Form", "60"))
        self.label_y0.setText(_translate("Form", "<html><head/><body><p>y<span style=\" vertical-align:sub;\">0</span></p></body></html>"))
        self.le_y0.setText(_translate("Form", "10"))
        self.label_N.setText(_translate("Form", "N"))
        self.le_N_applte.setText(_translate("Form", "70"))
        self.cb_exact.setText(_translate("Form", "Exact Solution"))
        self.cb_eem.setText(_translate("Form", "Explicit Euler Method"))
        self.cb_iem.setText(_translate("Form", "Improved Euler Method"))
        self.cb_rkm.setText(_translate("Form", "Runge-Kutta Method"))
        self.cb_eem_lte.setText(_translate("Form", "EEM LTE"))
        self.cb_iem_lte.setText(_translate("Form", "IEM LTE"))
        self.cb_rkm_lte.setText(_translate("Form", "RKM LTE"))
        self.pb_plot_applte.setText(_translate("Form", "Plot"))
        self.gb_app.setTitle(_translate("Form", "Exact solution and approximation graphs"))
        self.gb_lte.setTitle(_translate("Form", "Local truncation error graphs"))
        self.label_applte.setText(_translate("Form", "<html><head/><body><p>Plotted successfully</p></body></html>"))
        self.label_applte_colors.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#0000ff;\">Exact Solution - blue</span></p><p>Explicit Euler Method - black</p><p><span style=\" color:#ff0000;\">Improved Euler Method - red</span></p><p><span style=\" color:#00aa00;\">Runge-Kutta Method - green</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_applte), _translate("Form", "Approximations and LTE"))
        self.label_n0.setText(_translate("Form", "<html><head/><body><p>n<span style=\" vertical-align:sub;\">0</span></p></body></html>"))
        self.le_n0.setText(_translate("Form", "5"))
        self.label_N_2.setText(_translate("Form", "N"))
        self.le_N_gte.setText(_translate("Form", "100"))
        self.cb_eem_gte.setText(_translate("Form", "Explicit Euler Method"))
        self.cb_iem_gte.setText(_translate("Form", "Improved Euler Method"))
        self.cb_rkm_gte.setText(_translate("Form", "Runge-Kutta Method"))
        self.pb_plot_gte.setText(_translate("Form", "Plot"))
        self.gb_gte.setTitle(_translate("Form", "Global truncation error graphs"))
        self.label_gte.setText(_translate("Form", "<html><head/><body><p>Plotted successfully</p></body></html>"))
        self.label_gte_colors.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#0000ff;\">Exact Solution - blue</span></p><p>Explicit Euler Method - black</p><p><span style=\" color:#ff0000;\">Improved Euler Method - red</span></p><p><span style=\" color:#00aa00;\">Runge-Kutta Method - green</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_gte), _translate("Form", "GTE"))
        self.label.setText(_translate("Form", "<html><head/><body><p>F21. Differential Equations. Computational Practicum</p></body></html>"))

